FROM node:22.20.0-alpine3.22

WORKDIR /app

COPY packages/engine ./packages/engine
COPY package.json .
COPY package-lock.json .
COPY turbo.json .

RUN npm ci
RUN npm run build

ENTRYPOINT ["node", "packages/engine/dist/index.js"]